<?php


namespace app\components;


use yii\base\Component;
use yii\db\Query;
use yii\helpers\ArrayHelper;

class menuComponent extends Component {

    public $item = [];

    /**
     * @throws \yii\base\InvalidConfigException
     * @throws \yii\db\Exception
     */

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub

        return $this->getMenu();
    }


    public function getMenu() {
        $query = \Yii::createObject(Query::class);

        $menu = $query->select('*')
                      ->from('menu')
                      ->andWhere(['active' => 'Y'])
                      ->orderBy('position')
                      ->createCommand()
                      ->queryAll();

        if ($menu) {
            foreach ($menu as $k => $i) {
                $menu[$k] = [
                    'label' => $i['label'],
                    'url' => [
                        $i['url']
                    ],
                    'active' => $i['url'] === \yii\helpers\Url::to()

                ];
            }
        }
        $ip = "189.240.194.147";  //$_SERVER['REMOTE_ADDR']

        $auth = (\Yii::$app->user->isGuest) ? 'Войти' : 'Выйти(' . \Yii::$app->user->identity->email . ')';
        $url = (\Yii::$app->user->isGuest) ? \Yii::getAlias('@sign-in') : \Yii::getAlias('@log-out');
        $menu[] = [
            'label' => $auth,
            'url' => ['/' . $url],
            'active' => ($url === \yii\helpers\Url::to())
        ];

        $this->item = $menu;
        return $menu;
    }


}